from __future__ import annotations

import logging
import os
import smtplib

from email.message import EmailMessage
from typing import Any

from sqlalchemy.orm import Session

# Ensure .env is loaded even when this service
# is called from standalone scripts.
import app.core.config  # noqa: F401

from app.investments.models.fund_pipeline_incident import (
    FundPipelineIncident,
)


logger = logging.getLogger(__name__)


# =========================================================
# CONFIGURATION
# =========================================================

def _env_bool(
    name: str,
    default: bool = False,
) -> bool:
    value = os.getenv(name)

    if value is None:
        return default

    return value.strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def _get_email_config() -> dict[str, Any]:
    """
    Read pipeline email configuration from environment.
    """

    return {
        "enabled": _env_bool(
            "PIPELINE_ALERT_EMAIL_ENABLED",
            False,
        ),

        "host": os.getenv(
            "PIPELINE_ALERT_SMTP_HOST",
            "smtp.gmail.com",
        ),

        "port": int(
            os.getenv(
                "PIPELINE_ALERT_SMTP_PORT",
                "587",
            )
        ),

        "username": os.getenv(
            "PIPELINE_ALERT_SMTP_USERNAME"
        ),

        "password": os.getenv(
            "PIPELINE_ALERT_SMTP_PASSWORD"
        ),

        "from_email": os.getenv(
            "PIPELINE_ALERT_FROM_EMAIL"
        ),

        "to_email": os.getenv(
            "PIPELINE_ALERT_TO_EMAIL"
        ),
    }


# =========================================================
# CONFIG VALIDATION
# =========================================================

def _validate_email_config(
    config: dict[str, Any],
) -> None:
    """
    Validate required SMTP configuration.
    """

    required = {
        "host": config.get("host"),
        "port": config.get("port"),
        "username": config.get("username"),
        "password": config.get("password"),
        "from_email": config.get("from_email"),
        "to_email": config.get("to_email"),
    }

    missing = [
        key
        for key, value in required.items()
        if not value
    ]

    if missing:
        raise RuntimeError(
            "Missing pipeline alert email "
            "configuration: "
            + ", ".join(missing)
        )


# =========================================================
# EMAIL CONTENT
# =========================================================

def _build_incident_email(
    incident: FundPipelineIncident,
) -> EmailMessage:
    """
    Build an operational incident email.
    """

    config = _get_email_config()

    message = EmailMessage()

    message["Subject"] = (
        "[InvestiGenie] "
        f"{incident.severity} Pipeline Incident — "
        f"{incident.incident_code}"
    )

    message["From"] = config[
        "from_email"
    ]

    message["To"] = config[
        "to_email"
    ]

    body = f"""
InvestiGenie Operational Alert

----------------------------------------
INCIDENT DETAILS
----------------------------------------

Severity:
{incident.severity}

Incident Code:
{incident.incident_code}

Status:
{incident.status}

Message:
{incident.message}

Incident ID:
{incident.id}

First Detected:
{incident.first_detected_at}

Last Detected:
{incident.last_detected_at}

----------------------------------------

Please review the InvestiGenie pipeline
administration dashboard.

This is an automated operational alert
generated by InvestiGenie.
""".strip()

    message.set_content(
        body
    )

    return message


# =========================================================
# SMTP DELIVERY
# =========================================================

def _send_email(
    message: EmailMessage,
) -> None:
    """
    Deliver an email through configured SMTP.

    Raises an exception if delivery fails.
    """

    config = _get_email_config()

    _validate_email_config(
        config
    )

    with smtplib.SMTP(
        config["host"],
        config["port"],
        timeout=30,
    ) as smtp:

        smtp.ehlo()

        smtp.starttls()

        smtp.ehlo()

        smtp.login(
            config["username"],
            config["password"],
        )

        smtp.send_message(
            message
        )


# =========================================================
# PENDING INCIDENT ALERTS
# =========================================================

def send_pending_pipeline_alerts(
    db: Session,
) -> dict[str, Any]:
    """
    Send alerts for OPEN incidents that have not
    previously been successfully alerted.

    Important invariant:

        alert_sent = True

    is written ONLY after SMTP delivery succeeds.

    Therefore failed deliveries remain eligible for
    retry on the next execution.
    """

    config = _get_email_config()

    if not config["enabled"]:
        logger.info(
            "Pipeline email alerts are disabled."
        )

        return {
            "enabled": False,
            "pending": 0,
            "sent": 0,
            "failed": 0,
            "results": [],
        }

    _validate_email_config(
        config
    )

    incidents = (
        db.query(
            FundPipelineIncident
        )
        .filter(
            FundPipelineIncident.status
            == "OPEN",

            FundPipelineIncident.alert_sent
            == False,  # noqa: E712
        )
        .order_by(
            FundPipelineIncident.id.asc()
        )
        .all()
    )

    sent = 0
    failed = 0

    results: list[dict[str, Any]] = []

    for incident in incidents:

        try:
            message = (
                _build_incident_email(
                    incident
                )
            )

            _send_email(
                message
            )

            # Local import prevents unnecessary
            # service-level circular dependencies.
            from app.investments.services.fund_pipeline_incident_persistence_service import (
                mark_pipeline_incident_alert_sent,
            )

            mark_pipeline_incident_alert_sent(
                db=db,
                incident_id=incident.id,
            )

            sent += 1

            results.append(
                {
                    "incident_id":
                        incident.id,

                    "incident_code":
                        incident.incident_code,

                    "status":
                        "SENT",
                }
            )

            logger.info(
                "Pipeline incident alert sent. "
                "incident_id=%s code=%s",
                incident.id,
                incident.incident_code,
            )

        except Exception as exc:

            failed += 1

            results.append(
                {
                    "incident_id":
                        incident.id,

                    "incident_code":
                        incident.incident_code,

                    "status":
                        "FAILED",

                    "error":
                        (
                            f"{type(exc).__name__}: "
                            f"{exc}"
                        ),
                }
            )

            logger.exception(
                "Pipeline incident alert delivery "
                "failed. incident_id=%s code=%s",
                incident.id,
                incident.incident_code,
            )

    return {
        "enabled": True,
        "pending": len(incidents),
        "sent": sent,
        "failed": failed,
        "results": results,
    }