"""add fund nav history

Revision ID: 21f4ef1272ad
Revises: 3512b0e0680c
Create Date: 2026-08-09 16:04:33.644945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f4ef1272ad'
down_revision: Union[str, Sequence[str], None] = '3512b0e0680c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_profiles', 'annual_income',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'monthly_income',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'monthly_expenses',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'monthly_debt_payment',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('financial_profiles', 'total_savings',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'emergency_fund',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'total_assets',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'total_liabilities',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'existing_investments',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'insurance_cover',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'net_worth',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('financial_profiles', 'savings_rate',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('financial_profiles', 'debt_to_income_ratio',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('financial_profiles', 'emergency_months',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('financial_profiles', 'investment_ratio',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_financial_profiles_id'), 'financial_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_financial_profiles_user_id'), 'financial_profiles', ['user_id'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_financial_profiles_user_id'), table_name='financial_profiles')
    op.drop_index(op.f('ix_financial_profiles_id'), table_name='financial_profiles')
    op.alter_column('financial_profiles', 'investment_ratio',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('financial_profiles', 'emergency_months',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('financial_profiles', 'debt_to_income_ratio',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('financial_profiles', 'savings_rate',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('financial_profiles', 'net_worth',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'insurance_cover',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'existing_investments',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'total_liabilities',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'total_assets',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'emergency_fund',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'total_savings',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'monthly_debt_payment',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('financial_profiles', 'monthly_expenses',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'monthly_income',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('financial_profiles', 'annual_income',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
